### ISSUE TITLE
Copy missing from the Fingerprints section

### ISSUE THREAD

**Issue by j4james** [catseye/Funge-98#4]
When describing the 'contract' between the fingerprint and the fingerprint user, one of the bullet points is:
>When loaded, a fingerprint which implements A and B semantics should act something like:

But then no further copy follows that line. The earlier HTML version of the documentation had something like this:
>save(`A`); bind(`A`, myAsemantic()); save(`B`); bind(`B`, myBsemantic());

The next point has the same issue:
>When unloaded, the same fingerprint should act something like

And again no further copy. The earlier HTML documentation had:
>restore(`B`); restore(`A`);

**Comment by cpressey** [comment]
Yes.  Thank you.  There was also a bunch of verbiage missing in the section on `y`.  The patch restoring this copy can be found here: https://bitbucket.org/catseye/funge-98/commits/d4d97472b7d4b9c953f6c68aa578dd7c99e825fc

**Comment by cpressey** [comment]
...which has made it to Github here: https://github.com/catseye/Funge-98/commit/146a3f1a67184a8583bd3c6fc31777d7a992c352  Closing this issue.  Thanks!
