### ISSUE TITLE
Concurrent Funge Stack and Stack Stack

### ISSUE THREAD

**Issue by coffeenotfound** [catseye/Funge-98#9]
The spec doesn't explain some things in context of concurrent Funge. Especially which state is per thread and which is global. I'm specifically wondering about the stack stack: The spec does mention that each thread has it's own stack which gets copied when a thread is forked, but does each thread also have it's own stack stack? If yes, is the whole stack stack cloned on fork or only the TOSS?

**Comment by cpressey** [comment]
I think the reasonable interpretation is that each thread gets its own stack stack, but I think the other interpretation is possibly more entertaining.

**Comment by coffeenotfound** [comment]
I think I'm going with the most sane version which is stack stack clone on fork :smile:
